"use strict";

/* requires */
const utils = Mary.require("Utils");

/* components */
const ʹ = require("./commons");

/* constants */
const english = new Map();

/* commons */
const oldTestament = new Map([
  ["Genesis", {chaps: ʹ(50)}],
  ["Exodus", {chaps: ʹ(40)}],
  ["Leviticus", {chaps: ʹ(27)}],
  ["Numbers", {chaps: ʹ(36)}],
  ["Deuteronomy", {chaps: ʹ(34)}],
  ["Joshua", {chaps: ʹ(24)}],
  ["Judges", {chaps: ʹ(21)}],
  ["Ruth", {chaps: ʹ(4)}],
  ["1 Samuel", {chaps: ʹ(31)}],
  ["2 Samuel", {chaps: ʹ(24)}],
  ["1 Kings", {chaps: ʹ(22)}],
  ["2 Kings", {chaps: ʹ(25)}],
  ["1 Chronicles", {chaps: ʹ(29)}],
  ["2 Chronicles", {chaps: ʹ(36)}],
  ["Ezra", {chaps: ʹ(10)}],
  ["Nehemiah", {chaps: ʹ(13)}],
  ["Esther", {chaps: ʹ(10)}],
  ["Job", {chaps: ʹ(42)}],
  ["Psalms", {chaps: ʹ(150)}],
  ["Proverbs", {chaps: ʹ(31)}],
  ["Ecclesiastes", {chaps: ʹ(12)}],
  ["Song of Solomon", {chaps: ʹ(8)}],
  ["Isaiah", {chaps: ʹ(66)}],
  ["Jeremiah", {chaps: ʹ(52)}],
  ["Lamentations", {chaps: ʹ(5)}],
  ["Ezekiel", {chaps: ʹ(48)}],
  ["Daniel", {chaps: ʹ(12)}],
  ["Hosea", {chaps: ʹ(14)}],
  ["Joel", {chaps: ʹ(3)}],
  ["Amos", {chaps: ʹ(9)}],
  ["Obadiah", {chaps: ʹ(1)}],
  ["Jonah", {chaps: ʹ(4)}],
  ["Micah", {chaps: ʹ(7)}],
  ["Nahum", {chaps: ʹ(3)}],
  ["Habakkuk", {chaps: ʹ(3)}],
  ["Zephaniah", {chaps: ʹ(3)}],
  ["Haggai", {chaps: ʹ(2)}],
  ["Zechariah", {chaps: ʹ(14)}],
  ["Malachi", {chaps: ʹ(4)}]
]);

const newTestament = new Map([
  ["Matthew", {chaps: ʹ(28)}],
  ["Mark", {chaps: ʹ(16)}],
  ["Luke", {chaps: ʹ(24)}],
  ["John", {chaps: ʹ(21)}],
  ["Acts", {chaps: ʹ(28)}],
  ["Romans", {chaps: ʹ(16)}],
  ["1 Corinthians", {chaps: ʹ(16)}],
  ["2 Corinthians", {chaps: ʹ(13)}],
  ["Galatians", {chaps: ʹ(6)}],
  ["Ephesians", {chaps: ʹ(6)}],
  ["Philippians", {chaps: ʹ(4)}],
  ["Colossians", {chaps: ʹ(4)}],
  ["1 Thessalonians", {chaps: ʹ(5)}],
  ["2 Thessalonians", {chaps: ʹ(3)}],
  ["1 Timothy", {chaps: ʹ(6)}],
  ["2 Timothy", {chaps: ʹ(4)}],
  ["Titus", {chaps: ʹ(3)}],
  ["Philemon", {chaps: ʹ(1)}],
  ["Hebrews", {chaps: ʹ(13)}],
  ["James", {chaps: ʹ(5)}],
  ["1 Peter", {chaps: ʹ(5)}],
  ["2 Peter", {chaps: ʹ(3)}],
  ["1 John", {chaps: ʹ(5)}],
  ["2 John", {chaps: ʹ(1)}],
  ["3 John", {chaps: ʹ(1)}],
  ["Jude", {chaps: ʹ(1)}],
  ["Revelation", {chaps: ʹ(22)}]
]);

/* KJV */
const kjvApocrypha = new Map([
  ["1 Esdras", {chaps: ʹ(9)}],
  ["2 Esdras", {chaps: ʹ(16)}],
  ["Tobit", {chaps: ʹ(14)}],
  ["Judith", {chaps: ʹ(16)}],
  ["Rest of Esther", {chaps: ʹ("10-16")}],
  ["Wisdom of Solomon", {chaps: ʹ(19)}],
  ["Ecclesiasticus", {chaps: ʹ("P,1-51")}],
  ["Baruch", {chaps: ʹ(5)}],
  ["Epistle of Jeremiah", {chaps: ʹ(1)}],
  ["Song of the Three Children", {chaps: ʹ(1)}],
  ["History of Susanna", {chaps: ʹ(1)}],
  ["Bel and the Dragon", {chaps: ʹ(1)}],
  ["Prayer of Manasseh", {chaps: ʹ(1)}],
  ["1 Maccabees", {chaps: ʹ(16)}],
  ["2 Maccabees", {chaps: ʹ(15)}]
]);
const kjv = utils.map.combine(
  oldTestament,
  kjvApocrypha,
  newTestament
);
english.set("KJV", kjv);
english.set("KJV 1872-1888", kjv); // need to put apocrypha after NT

/* KJV 1611 */
english.set("KJV 1611", new Map([
  ["Genesis", {chaps: ʹ(50), alt: "Geneſis"}],
  ["Exodus", {chaps: ʹ(40)}],
  ["Leviticus", {chaps: ʹ(27), alt: "Leuiticus"}],
  ["Numbers", {chaps: ʹ(36)}],
  ["Deuteronomy", {chaps: ʹ(34), alt: "Deuteronomie"}],
  ["Joshua", {chaps: ʹ(24), alt: "Ioſhua"}],
  ["Judges", {chaps: ʹ(21), alt: "Iudges"}],
  ["Ruth", {chaps: ʹ(4)}],
  ["1 Samuel", {chaps: ʹ(31)}],
  ["2 Samuel", {chaps: ʹ(24)}],
  ["1 Kings", {chaps: ʹ(22)}],
  ["2 Kings", {chaps: ʹ(25)}],
  ["1 Chronicles", {chaps: ʹ(29)}],
  ["2 Chronicles", {chaps: ʹ(36)}],
  ["Ezra", {chaps: ʹ(10)}],
  ["Nehemiah", {chaps: ʹ(13)}],
  ["Esther", {chaps: ʹ(10), alt: "Eſther"}],
  ["Job", {chaps: ʹ(42), alt: "Iob"}],
  ["Psalms", {chaps: ʹ(150), alt: "Pſalmes"}],
  ["Proverbs", {chaps: ʹ(31), alt: "Prouerbs"}],
  ["Ecclesiastes", {chaps: ʹ(12), alt: "Eccleſiaſtes"}],
  ["Song of Solomon", {chaps: ʹ(8)}],
  ["Isaiah", {chaps: ʹ(66), alt: "Iſaiah"}],
  ["Jeremiah", {chaps: ʹ(52), alt: "Ieremiah"}],
  ["Lamentations", {chaps: ʹ(5)}],
  ["Ezekiel", {chaps: ʹ(48)}],
  ["Daniel", {chaps: ʹ(12)}],
  ["Hosea", {chaps: ʹ(14), alt: "Hoſea"}],
  ["Joel", {chaps: ʹ(3), alt: "Ioel"}],
  ["Amos", {chaps: ʹ(9)}],
  ["Obadiah", {chaps: ʹ(1)}],
  ["Jonah", {chaps: ʹ(4), alt: "Ionah"}],
  ["Micah", {chaps: ʹ(7)}],
  ["Nahum", {chaps: ʹ(3)}],
  ["Habakkuk", {chaps: ʹ(3)}],
  ["Zephaniah", {chaps: ʹ(3)}],
  ["Haggai", {chaps: ʹ(2)}],
  ["Zechariah", {chaps: ʹ(14)}],
  ["Malachi", {chaps: ʹ(4)}],
  ["1 Esdras", {chaps: ʹ(9), alt: "1 Eſdras"}],
  ["2 Esdras", {chaps: ʹ(16), alt: "2 Eſdras"}],
  ["Tobit", {chaps: ʹ(14)}],
  ["Judith", {chaps: ʹ(16), alt: "Iudeth"}],
  ["Rest of Esther", {chaps: ʹ("10-16"), alt: "Reſt of Eſther"}],
  ["Wisdom of Solomon", {chaps: ʹ(19), alt: "Wiſedome of Solomon"}],
  ["Ecclesiasticus", {chaps: ʹ("P,1-51"), alt: "Eccleſiaſticus"}],
  ["Baruch and Epistle of Jeremiah", {chaps: ʹ(6), alt: "Baruch and Epiſtle of Ieremiah"}],
  ["Song of the Three Children", {chaps: ʹ(1)}],
  ["Susanna", {chaps: ʹ(1), alt: "Suſanna"}],
  ["Bel and the Dragon", {chaps: ʹ(1)}],
  ["Prayer of Manasseh", {chaps: ʹ(1), alt: "Prayer of Manaſſeh"}],
  ["1 Maccabees", {chaps: ʹ(16)}],
  ["2 Maccabees", {chaps: ʹ(15)}],
  ["Matthew", {chaps: ʹ(28)}],
  ["Mark", {chaps: ʹ(16), alt: "Marke"}],
  ["Luke", {chaps: ʹ(24)}],
  ["John", {chaps: ʹ(21), alt: "Iohn"}],
  ["Acts", {chaps: ʹ(28), alt: "Actes"}],
  ["Romans", {chaps: ʹ(16)}],
  ["1 Corinthians", {chaps: ʹ(16)}],
  ["2 Corinthians", {chaps: ʹ(13)}],
  ["Galatians", {chaps: ʹ(6)}],
  ["Ephesians", {chaps: ʹ(6), alt: "Epheſians"}],
  ["Philippians", {chaps: ʹ(4)}],
  ["Colossians", {chaps: ʹ(4), alt: "Coloſsians"}],
  ["1 Thessalonians", {chaps: ʹ(5), alt: "1 Theſſalonians"}],
  ["2 Thessalonians", {chaps: ʹ(3), alt: "2 Theſſalonians"}],
  ["1 Timothy", {chaps: ʹ(6), alt: "1 Timotheus"}],
  ["2 Timothy", {chaps: ʹ(4), alt: "2 Timotheus"}],
  ["Titus", {chaps: ʹ(3)}],
  ["Philemon", {chaps: ʹ(1)}],
  ["Hebrews", {chaps: ʹ(13), alt: "Hebrewes"}],
  ["James", {chaps: ʹ(5), alt: "Iames"}],
  ["1 Peter", {chaps: ʹ(5)}],
  ["2 Peter", {chaps: ʹ(3)}],
  ["1 John", {chaps: ʹ(5), alt: "1 Iohn"}],
  ["2 John", {chaps: ʹ(1), alt: "2 Iohn"}],
  ["3 John", {chaps: ʹ(1), alt: "3 Iohn"}],
  ["Jude", {chaps: ʹ(1), alt: "Iude"}],
  ["Revelation", {chaps: ʹ(22), alt: "Reuelation"}]
]));

/* WEBA */
const webaApocrypha = new Map([
  ["Tobit", {chaps: ʹ(14)}],
  ["Judith", {chaps: ʹ(16)}],
  ["Esther (Greek)", {chaps: ʹ(10)}],
  ["Wisdom of Solomon", {chaps: ʹ(19)}],
  ["Sirach", {chaps: ʹ("P,1-51")}],
  ["Baruch", {chaps: ʹ(6)}],
  ["1 Maccabees", {chaps: ʹ(16)}],
  ["2 Maccabees", {chaps: ʹ(15)}],
  ["1 Esdras", {chaps: ʹ(9)}],
  ["Prayer of Manasses", {chaps: ʹ(1)}],
  ["Psalm 151", {chaps: ʹ(1)}],
  ["3 Maccabees", {chaps: ʹ(7)}],
  ["2 Esdras", {chaps: ʹ(16)}],
  ["4 Maccabees", {chaps: ʹ(18)}],
  ["Daniel (Greek)", {chaps: ʹ(14)}]
]);
const weba = utils.map.combine(
  oldTestament,
  webaApocrypha,
  newTestament
);
english.set("WEBA", weba);

/* Brenton's English OT */
english.set("Brenton's English OT", new Map([
  ["Genesis", {chaps: ʹ(50), alt: "ΓΕΝΕΣΙΣ"}],
  ["Exodus", {chaps: ʹ(40), alt: "ΕΞΟΔΟΣ"}],
  ["Leviticus", {chaps: ʹ(27), alt: "ΛΕΥΙΤΙΚΟΝ"}],
  ["Numbers", {chaps: ʹ(36), alt: "ΑΡΙΘΜΟΙ"}],
  ["Deuteronomy", {chaps: ʹ(34), alt: "ΔΕΥΤΕΡΟΝΟΜΙΟΝ"}],
  ["Joshua", {chaps: ʹ(24), alt: "ΙΗΣΟΥΣ ΝΑΥΗ"}],
  ["Judges", {chaps: ʹ(21), alt: "ΚΡΙΤΑΙ"}],
  ["Ruth", {chaps: ʹ(4), alt: "ΡΟΥΘ"}],
  ["1 Samuel", {chaps: ʹ(31), alt: "ΒΑΣΙΛΕΙΩΝ Αʹ/ΣΑΜΟΥΗΛ Αʹ"}],
  ["2 Samuel", {chaps: ʹ(24), alt: "ΒΑΣΙΛΕΙΩΝ Βʹ/ΣΑΝΟΥΗΛ Βʹ"}],
  ["1 Kings", {chaps: ʹ(22), alt: "ΒΑΣΙΛΕΙΩΝ Γʹ/ΒΑΣΙΛΕΙΩΝ Αʹ"}],
  ["2 Kings", {chaps: ʹ(25), alt: "ΒΑΣΙΛΕΙΩΝ Δʹ/ΒΑΣΙΛΕΙΩΝ Βʹ"}],
  ["1 Chronicles", {chaps: ʹ(29), alt: "ΠΑΡΑΛΕΙΠΟΜΕΝΩΝ Αʹ/ΧΡΟΝΙΚΩΝ Αʹ"}],
  ["2 Chronicles", {chaps: ʹ(36), alt: "ΠΑΡΑΛΕΙΠΟΜΕΝΩΝ Βʹ/ΧΡΟΝΙΚΩΝ Βʹ"}],
  ["Ezra", {chaps: ʹ(10), alt: "ΕΣΔΡΑΣ"}],
  ["Nehemiah", {chaps: ʹ(13), alt: "ΝΕΕΜΙΑΣ"}],
  ["Esther", {chaps: ʹ(10), alt: "ΕΣΘΗΡ"}],
  ["Job", {chaps: ʹ(42), alt: "ΙΩΒ"}],
  ["Psalms", {chaps: ʹ(150), alt: "ΨΑΛΜΟΙ"}],
  ["Proverbs", {chaps: ʹ(29), alt: "ΠΑΡΟΙΜΙΑΙ"}],
  ["Ecclesiastes", {chaps: ʹ(12), alt: "ΕΚΚΛΗΣΙΑΣΤΗΣ"}],
  ["Song of Solomon", {chaps: ʹ(8), alt: "ΑΣΜΑ/ΑΣΜΑ ΑΣΜΑΤΩΝ"}],
  ["Isaiah", {chaps: ʹ(66), alt: "ΗΣΑΙΑΣ"}],
  ["Jeremiah", {chaps: ʹ(52), alt: "ΙΕΡΕΜΙΑΣ"}],
  ["Lamentations", {chaps: ʹ(5), alt: "ΘΡΗΝΟΙ/ΘΡΗΝΟΙ ΙΕΡΕΜΙΟΥ"}],
  ["Ezekiel", {chaps: ʹ(48), alt: "ΙΕΖΕΚΙΗΛ"}],
  ["Daniel", {chaps: ʹ(12), alt: "ΔΑΝΙΗΛ"}],
  ["Hosea", {chaps: ʹ(14), alt: "ΩΣΗΕ"}],
  ["Joel", {chaps: ʹ(3), alt: "ΙΩΗΛ"}],
  ["Amos", {chaps: ʹ(9), alt: "ΑΜΩΣ"}],
  ["Obadiah", {chaps: ʹ(1), alt: "ΟΒΔΙΟΥ"}],
  ["Jonah", {chaps: ʹ(4), alt: "ΙΩΝΑΣ"}],
  ["Micah", {chaps: ʹ(7), alt: "ΜΙΧΑΙΑΣ"}],
  ["Nahum", {chaps: ʹ(3), alt: "ΝΑΟΥΜ"}],
  ["Habakkuk", {chaps: ʹ(3), alt: "ΑΜΒΑΚΟΥΜ"}],
  ["Zephaniah", {chaps: ʹ(3), alt: "ΣΟΦΟΝΙΑΣ"}],
  ["Haggai", {chaps: ʹ(2), alt: "ΑΓΓΑΙΟΣ"}],
  ["Zechariah", {chaps: ʹ(14), alt: "ΖΑΧΑΡΙΑΣ"}],
  ["Malachi", {chaps: ʹ(4), alt: "ΜΑΛΑΧΙΑΣ/ΑΓΓΕΛΟΣ"}],
  ["1 Esdras", {chaps: ʹ(9), alt: "ΕΣΔΡΑΣ Αʹ"}],
  ["Tobit", {chaps: ʹ(14), alt: "ΤΩΒΙΤ"}],
  ["Judith", {chaps: ʹ(16), alt: "ΙΟΥΔΙΘ"}],
  ["Wisdom of Solomon", {chaps: ʹ(19), alt: "ΣΟΦΙΑ ΣΑΛΩΜΩΝΟΣ"}],
  ["Ecclesiasticus", {chaps: ʹ(51), alt: "ΣΟΦΙΑ ΣΙΡΑΧ"}],
  ["Baruch", {chaps: ʹ(5), alt: "ΒΑΡΟΥΧ"}],
  ["Epistle of Jeremiah", {chaps: ʹ(1), alt: "ΕΠΙΣΤΟΛΗ ΙΕΡΕΜΙΟΥ"}],
  ["Song of the Three Children", {chaps: ʹ(1), alt: "ΤΩΝ ΤΡΙΩΝ ΠΑΙΔΩΝ ΑΙΝΕΣΙΣ"}],
  ["Susanna", {chaps: ʹ(1), alt: "ΣΟΥΣΑΝΝΑ"}],
  ["Bel and the Dragon", {chaps: ʹ(1), alt: "ΒΗΛ ΚΑΙ ΔΡΑΚΩΝ"}],
  ["1 Maccabees", {chaps: ʹ(16), alt: "ΜΑΚΚΑΒΑΙΩΝ Αʹ"}],
  ["2 Maccabees", {chaps: ʹ(15), alt: "ΜΑΚΚΑΒΑΙΩΝ Βʹ"}],
  ["3 Maccabees", {chaps: ʹ(7), alt: "ΜΑΚΚΑΒΑΙΩΝ Γʹ"}],
  ["4 Maccabees", {chaps: ʹ(18), alt: "ΜΑΚΚΑΒΑΙΩΝ Δʹ"}],
  ["Prayer of Manasseh", {chaps: ʹ(1), alt: "ΠΡΟΣΕΥΧΗ ΜΑΝΑΣΣΗ"}]
]));

/* exports */
module.exports = english;
